# Generated by Django 2.2.1 on 2019-05-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='dataHora',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
