# Generated by Django 2.2.1 on 2019-05-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190513_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
