# Generated by Django 2.2.1 on 2019-05-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190517_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='diasDeFebre',
            new_name='dias',
        ),
    ]
