# Generated by Django 2.2.1 on 2019-05-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190518_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='temperatura',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
